name: 01.building blocks
on: push

jobs:
   echo-hello:
      runs-on: ubuntu-latest
      steps: 
         - name: say echo-hello
           run: echo "hello world"

   echo-goodby:
      runs-on: ubuntu-latest
      steps:
         - name: Failed - name    
           run: |
              echo " I will fail"
              exit 1
         - name: Say - goodbye
           run: echo "Good by"
         
